package main

import (
	"fmt"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	deprecationComment = "// Deprecated: Do not use."
)

const (
	bindModeDefault            = "default"
	bindModePathQuery          = "path_query"
	bindModePathBody           = "path_body"
	bindModePathQueryBodyField = "path_query_body_field"
)

// generateFile 为每个包含 service 的 proto 文件生成 _echo.pb.go。
func generateFile(gen *protogen.Plugin, file *protogen.File, config generatorConfig) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	// 收集所有服务将生成的顶层标识符，用于 import alias 避让
	reservedAliases := []string{
		"context",
		"errors",
		"mime",
		"echo",
		"emptypb",
		"runtime",
	}
	for _, svc := range file.Services {
		name := svc.GoName
		reservedAliases = append(reservedAliases,
			name,              // 服务结构体，如 AuthService
			name+"HTTPServer", // 接口
		)
	}
	imports := newImportManager(
		file.GoImportPath,
		config.packageNames,
		reservedAliases...,
	)

	type renderedService struct {
		Deprecated bool
		Data       *service
	}

	renderedServices := make([]renderedService, 0, len(file.Services))
	needsEmptyPb := false

	for _, protoService := range file.Services {
		sd, serviceNeedsEmpty := genService(gen, file, protoService, config, imports)
		renderedServices = append(renderedServices, renderedService{
			Deprecated: protoService.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated(),
			Data:       sd,
		})
		needsEmptyPb = needsEmptyPb || serviceNeedsEmpty
	}

	filename := file.GeneratedFilenamePrefix + "_echo.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-echo. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// 检查特殊响应模式，决定是否需要额外 import
	needsMime := false
	for _, rs := range renderedServices {
		for _, m := range rs.Data.Methods {
			if m.IsFileDownload {
				needsMime = true
			}
		}
	}

	g.P("import (")
	g.P(`context "context"`)
	g.P(`errors "errors"`)
	g.P(`"slices"`)
	if needsMime {
		g.P(`"mime"`)
	}
	g.P("echo ", `"github.com/labstack/echo/v4"`)
	if needsEmptyPb {
		g.P(`"google.golang.org/protobuf/types/known/emptypb"`)
	}
	g.P(`runtime "github.com/orzmoe/protoc-gen-go-echo/runtime"`)

	for _, fileImport := range imports.Imports() {
		g.P(fileImport.Alias, ` "`, fileImport.Path, `"`)
	}

	g.P(")")
	g.P()

	// 如果需要Empty类型，定义别名
	if needsEmptyPb {
		g.P("type Empty = emptypb.Empty")
		g.P()
	}

	for _, renderedService := range renderedServices {
		if renderedService.Deprecated {
			g.P("//")
			g.P(deprecationComment)
		}
		content, err := renderedService.Data.execute()
		if err != nil {
			gen.Error(fmt.Errorf("%s.%s: 渲染模板失败: %w", file.Desc.Path(), renderedService.Data.Name, err))
			continue
		}
		g.P(content)
	}
	return g
}

func genService(gen *protogen.Plugin, file *protogen.File, s *protogen.Service, config generatorConfig, imports *importManager) (*service, bool) {
	sd := &service{
		Name:          s.GoName,
		FullName:      string(s.Desc.FullName()),
		FilePath:      file.Desc.Path(),
		ResponseStyle: config.responseStyle,
	}
	needsEmptyPb := false
	methodCounts := make(map[string]int)
	seenInterfaceMethods := make(map[string]struct{})
	routes := make(map[string]string)

	for _, method := range s.Methods {
		generatedMethods, methodNeedsEmpty := genMethod(gen, file, method, imports)
		needsEmptyPb = needsEmptyPb || methodNeedsEmpty
		for _, generatedMethod := range generatedMethods {
			generatedMethod.Num = methodCounts[generatedMethod.Name]
			methodCounts[generatedMethod.Name]++

			routeKey := generatedMethod.Method + " " + generatedMethod.Path
			if previousMethod, exists := routes[routeKey]; exists {
				gen.Error(fmt.Errorf("%s.%s: 检测到重复路由 %s（已被 %s 使用）", file.Desc.Path(), method.GoName, routeKey, previousMethod))
				continue
			}
			routes[routeKey] = generatedMethod.Name

			sd.Methods = append(sd.Methods, generatedMethod)
			if _, exists := seenInterfaceMethods[generatedMethod.Name]; exists {
				continue
			}
			seenInterfaceMethods[generatedMethod.Name] = struct{}{}
			sd.InterfaceMethods = append(sd.InterfaceMethods, generatedMethod)
		}
	}
	return sd, needsEmptyPb
}

func genMethod(gen *protogen.Plugin, file *protogen.File, m *protogen.Method, imports *importManager) ([]*method, bool) {
	var methods []*method
	options, err := parseMethodOptions(m)
	if err != nil {
		gen.Error(fmt.Errorf("%s.%s: %w", file.Desc.Path(), m.GoName, err))
		return methods, false
	}
	needsEmptyPb := isGoogleProtobufEmpty(m.Input) || isGoogleProtobufEmpty(m.Output)

	if err := normalizeMethodOptions(&options); err != nil {
		gen.Error(fmt.Errorf("%s.%s: %w", file.Desc.Path(), m.GoName, err))
		return methods, needsEmptyPb
	}

	if err := validateMethodOptions(options); err != nil {
		gen.Error(fmt.Errorf("%s.%s: %w", file.Desc.Path(), m.GoName, err))
		return methods, needsEmptyPb
	}

	if options.setAuthCookie {
		if err := validateAuthCookieResponse(m.Output); err != nil {
			gen.Error(fmt.Errorf("%s.%s: %w", file.Desc.Path(), m.GoName, err))
			return methods, needsEmptyPb
		}
	}

	if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
		gen.Error(fmt.Errorf("%s.%s: 暂不支持 streaming RPC 生成 HTTP handler", file.Desc.Path(), m.GoName))
		return methods, needsEmptyPb
	}

	// 统一收集方法注释，避免后续多次重复调用 collectMethodComments
	combinedComments := collectMethodComments(m)

	// 检查注释是否包含"内部调用"标记，如果是则跳过 HTTP 生成
	if isInternalFromComments(combinedComments) {
		return methods, needsEmptyPb
	}

	// 检查是否缺少 @summary 注释
	summary, description := parseCommentsContent(combinedComments)
	if summary == "" {
		gen.Error(fmt.Errorf("%s.%s: 缺少 @summary 注释，请添加接口名称", file.Desc.Path(), m.GoName))
	}

	// 存在 http rule 配置
	rule, ok := proto.GetExtension(m.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
	if rule != nil && ok {
		for _, bind := range rule.AdditionalBindings {
			builtMethod, err := buildHTTPRule(file, m, bind, options, imports, summary, description)
			if err != nil {
				gen.Error(err)
				return methods, needsEmptyPb
			}
			methods = append(methods, builtMethod)
		}
		builtMethod, err := buildHTTPRule(file, m, rule, options, imports, summary, description)
		if err != nil {
			gen.Error(err)
			return methods, needsEmptyPb
		}
		methods = append(methods, builtMethod)
		return methods, needsEmptyPb
	}

	// 不存在走默认流程
	builtMethod, err := defaultMethod(file, m, options, imports, summary, description)
	if err != nil {
		gen.Error(err)
		return methods, needsEmptyPb
	}
	methods = append(methods, builtMethod)
	return methods, needsEmptyPb
}
